### ISSUE TITLE
the example event_display throw exception

### ISSUE THREAD

**Issue by etherlai** [elegantmonkeys/python-kncloudevents#7]
Exception happened during processing of request from ('127.0.0.1', 57794)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/site-packages/kncloudevents/kncloudevents.py", line 44, in do_POST
    event = m.FromRequest(event, headers, data, json.loads)
  File "/usr/local/lib/python3.7/site-packages/cloudevents/sdk/marshaller.py", line 68, in FromRequest
    return cnvrtr.read(event, headers, body, data_unmarshaller)
  File "/usr/local/lib/python3.7/site-packages/cloudevents/sdk/converters/binary.py", line 43, in read
    event.UnmarshalBinary(headers, body, data_unmarshaller)
  File "/usr/local/lib/python3.7/site-packages/cloudevents/sdk/event/base.py", line 142, in UnmarshalBinary
    self.Set("data", data_unmarshaller(body))
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not StringIO

**Comment by etherlai** [comment]
post add -H "Content-Type: application/json".can i handler other Content-Type?

**Comment by ron212** [comment]
Hey,
The CloudEvents v0.2 we are using here support only `application/json` or `application/cloudevents+json` content types.
